# Generated by Django 2.0.4 on 2018-04-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='division')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=6)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division')),
            ],
        ),
    ]
