# Generated by Django 2.0.4 on 2018-04-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180428_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('pay_per_month', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='study')),
                ('study_type', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('math', 'Math'), ('other', 'Others')], max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division')),
            ],
        ),
    ]
