# Generated by Django 2.0.4 on 2018-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English'), ('math', 'Math'), ('other', 'Others')], max_length=10),
        ),
    ]
