# Generated by Django 2.0.4 on 2018-05-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180502_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('square_feed', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=11)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='property')),
                ('condition', models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor')], max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bath_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.BathRoom')),
                ('bed_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.BedRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inches', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=11)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='television')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='TVCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='television',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TVCategory'),
        ),
        migrations.AddField(
            model_name='television',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TVCategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division'),
        ),
    ]
