# Generated by Django 2.0.4 on 2018-05-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180502_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TVCategory'),
        ),
        migrations.AlterField(
            model_name='television',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category'),
        ),
    ]
