# Generated by Django 2.0.4 on 2018-05-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180502_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=11)),
                ('price', models.IntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], max_length=6)),
                ('computing_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], max_length=9)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputingBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='computing',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ComputingBrand'),
        ),
        migrations.AddField(
            model_name='computing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category'),
        ),
        migrations.AddField(
            model_name='computing',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Division'),
        ),
    ]
