# Generated by Django 2.0.4 on 2018-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20180503_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computing',
            name='image',
            field=models.ImageField(upload_to='computing'),
        ),
    ]
