# Generated by Django 2.0.4 on 2018-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20180503_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computing',
            name='computing_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('headphone', 'Headphone'), ('mouse', 'Mouse'), ('keyboard', 'Keyboard')], max_length=9),
        ),
    ]
