# Generated by Django 2.0.4 on 2018-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('colum1', models.CharField(max_length=35)),
                ('colum2', models.CharField(max_length=35)),
                ('colum3', models.CharField(blank=True, max_length=35, null=True)),
                ('colum4', models.CharField(blank=True, max_length=35, null=True)),
                ('colum5', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
