# Generated by Django 2.0.4 on 2018-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_updateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='present_address',
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
