# Generated by Django 2.0.4 on 2018-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20180502_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateprofile',
            name='phone_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
