# Generated by Django 2.0.4 on 2018-05-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_updateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
